name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  google_sign_in: ^6.2.2
  file_picker: ^9.0.2
  open_file: ^3.3.2
  path: ^1.8.3
  video_player: ^2.9.3
  chewie: ^1.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
