name: FormatX
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter_ffmpeg_utils:
    path: ../flutter_ffmpeg_utils
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  google_sign_in: ^6.2.2
  file_picker: ^9.0.2
  video_player: ^2.9.3
  chewie: ^1.10.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^11.4.0
  firebase_storage: ^12.4.5
  pdf: ^3.11.3
  printing: ^5.14.2
  open_filex: ^4.7.0
  share_plus: ^10.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
