// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials
  // Generate this file with credentials with the FlutterFire CLI
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHcLBtt9KwcbodzpQahPdfCdRarnMPNM',
    appId: '1:1019977481684:web:e829dda3c0e690f5d62a41',
    messagingSenderId: '1019977481684',
    projectId: 'formatx-30fed',
    authDomain: 'formatx-30fed.firebaseapp.com',
    storageBucket: 'formatx-30fed.firebasestorage.app',
    measurementId: 'G-FJFRLYHDDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknY3g4_P-5fnWU-7rTVTnMqDaKF1ftic',
    appId: '1:1019977481684:android:e7bfc22c848cb57ad62a41',
    messagingSenderId: '1019977481684',
    projectId: 'formatx-30fed',
    storageBucket: 'formatx-30fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2UXqWCKq7jf-XcH0XpAAgIItDxU1uA5s',
    appId: '1:1019977481684:ios:0b8c05a69d61eb53d62a41',
    messagingSenderId: '1019977481684',
    projectId: 'formatx-30fed',
    storageBucket: 'formatx-30fed.firebasestorage.app',
    iosBundleId: 'com.example.format_x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2UXqWCKq7jf-XcH0XpAAgIItDxU1uA5s',
    appId: '1:1019977481684:ios:0b8c05a69d61eb53d62a41',
    messagingSenderId: '1019977481684',
    projectId: 'formatx-30fed',
    storageBucket: 'formatx-30fed.firebasestorage.app',
    iosBundleId: 'com.example.format_x',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByHcLBtt9KwcbodzpQahPdfCdRarnMPNM',
    appId: '1:1019977481684:web:0650c201b831b6bfd62a41',
    messagingSenderId: '1019977481684',
    projectId: 'formatx-30fed',
    authDomain: 'formatx-30fed.firebaseapp.com',
    storageBucket: 'formatx-30fed.firebasestorage.app',
    measurementId: 'G-JN4DVRRFDN',
  );
}
